#!/bin/bash

GAME_PATH="$(realpath ~/Library/Application\ Support/Steam/steamapps/common/Crusader\ Kings\ III)"

function log-error {
    tail -f ../../logs/error.log
}

function log-debug {
    tail -f ../../logs/debug.log
}

function rg_gamefiles {
    rg -i $1 "$GAME_PATH/game"
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
